#!/bin/bash

config="$HOME/.emprimt"
mailbox="$config/primtbox"

if [[ "$1" == "-h" ]]; then less /usr/share/doc/emprimt/doc; exit; fi

main() {
  while IFS="" read -r printer; do
    [[ $( lpstat -p -d | awk '$1=="printer" {print $2}' | grep -c "$printer" ) -eq 0 ]] \
      && continue

    cache="$mailbox/cache/$printer"
    mkdir --parents "$cache"

    for f in $mailbox/new/*; do
      [ ! -f "$f" ] && continue
      [[ $( grep -ce "^Subject:.*$printer.*$" "$f" ) -ne 0 ]] \
        && munpack -C "$cache" "$f"
      rm "$f"
    done

    for f in $cache/*; do
      [ ! -f "$f" ] && continue
      lpr -P "$printer" "$f"
    done

    rm -r "$cache"
  done <"$config/printers"
}

fetchmail

main
