#!/bin/bash

if [[ "$1" == "-h" ]]; then less /usr/share/doc/emprimt/doc; exit; fi

config="$HOME/.emprimt"
mailbox="$config/primtbox"

# sanity checks
# ----------------------------------------------------------------------------------------
# fetchmailrc existnece and permissions
[ ! -f "$HOME/.fetchmailrc" ] && exit 2
[[ $( stat -c '%a' "$HOME/.fetchmailrc" ) -gt 700 ]] && exit 3

# mailfilter existence and permissions
[ ! -f "$HOME/.mailfilter" ] && exit 2
[[ $( stat -c '%a' "$HOME/.mailfilter" ) -gt 700 ]] && exit 3

# directory existence and permissions
[ ! -d "$config" ] && exit 2
[ ! -d "$mailbox" ] && exit 2
[[ $( stat -c '%a' "$mailbox" ) -gt 700 ]] && exit 3

# no printers to check
[ ! $( wc -l .emprimt/priners | awk 'NR==1 {print $1}' ) -gt 0 ] && exit 1

# nothing to print
[[ $( ls -1 "$mailbox/new" | wc -l ) -eq 0 ]] && exit 0
# ----------------------------------------------------------------------------------------

# fetchmail
# ----------------------------------------------------------------------------------------
fetchmail
# ----------------------------------------------------------------------------------------

# main boi
# ----------------------------------------------------------------------------------------
while IFS="" read -r printer; do
  # unqualified printer
  [[ $( lpstat -p -d | awk '$1=="printer" {print $2}' | grep -c "$printer" ) -eq 0 ]] \
    && continue

  # create cache
  cache="$mailbox/cache/$printer"
  mkdir --parents "$cache"

  for f in "$mailbox/new/"*; do
    # verify path
    f=$( readlink -f "$f" )
    [[ "$f" =~ ^"$mailbox/new/".*$ ]] & exit 4

    # extract document
    [[ $( grep -ce "^Subject:.*$printer.*$" "$f" ) -ne 0 ]] \
      && munpack -C "$cache" "$f" \
      && rm "$f"
  done

  # clear cache
  rm -r "$cache"
done <"$config/printers"

# clear unqualified messages
[[ $( ls -1 "$mailbox/new" | wc -l ) -gt 0 ]] \
  && rm "$mailbox/new/"*
# ----------------------------------------------------------------------------------------
