#!/bin/bash

printf "\n%s" "Begin install of emprimt."

user=emprimt

bin=/usr/bin
doc=/usr/share/doc/emprimt

enable=false
interval="05 * * * *"

force=false

except() { # <except text>
  echo "$1" > /dev/stderr
  exit 2
}

install_config() { # <source> <dest>
  [ -f "$2" ] || [[ "$force" != false ]] && return
  echo "Installing $1..."
  sudo -u "$user" cp -v "$1" "$2" || except "Error installing $1."
}

__doc__=(
  "must be run as superuser."
  "usage: ./install -h"
  "       ./install [ --user <emprimt_user> (default \`$user')"
  "                   --enable (i.e. install cron; default false)"
  "                   --force (i.e. force re-install configs) ]"
)

show_doc() {
  printf "%s\n" "${__doc__[@]}" > /dev/stderr
}

if [[ "$USER" != "root" ]]; then show_doc; exit 1; fi

while [ "$#" -gt 0 ]; do
  case "$1" in
    --user)
      user="$2"
      shift 2
      ;;
    --enable)
      enable=true
      shift 1
      ;;
    --force)
      force=true
      shift 1
      ;;
    -h)
      show_doc
      exit
      ;;
    *)
      show_doc
      exit 1
      ;;
  esac
done

# create user
# ----------------------------------------------------------------------------------------
create_user() {
  echo "Creating $user user..."
  useradd "$user"
  echo "Set a password for $user:"
  passwd "$user"
}

[[ $( awk '{print $1}' /etc/passwd | grep -c "$user" ) -eq 0 ]] && create_user

HOME=$( awk -F: '$1=="'$user'" {print $6}' /etc/passwd )
[ -d "$HOME" ] || except "Error with home directory."

config="$HOME/.emprimt"
mailbox="$config/primtbox"
echo "Will install emprimt at $config."
# ----------------------------------------------------------------------------------------

# make directories
# ----------------------------------------------------------------------------------------
echo "Making directories..."
mkdir -v --parents "$doc"
sudo -u "$user" mkdir -v --parents "$config" "$mailbox"
[ -d "$mailbox" ] || sudo -u "$user" maildirmake "$mailbox"
chmod -v 700 "$mailbox"
echo "Done."
# ----------------------------------------------------------------------------------------

# install user files
# ----------------------------------------------------------------------------------------
echo "Installing $user user files..."
install_config ./sample_fetchmailrc "$HOME/.fetchmailrc"
install_config ./mailfilter "$HOME/.mailfilter"
chmod -v 600 "$HOME/.fetchmailrc" "$HOME/.mailfilter" || except "Error installing rcs."
sudo -u "$user" touch "$config/printer" || except "Error creating printer list."
echo "Done."
# ----------------------------------------------------------------------------------------

# install doc, bin
# ----------------------------------------------------------------------------------------
echo "Installing executable and doc..."
cp -v ./doc "$doc/doc" || except "Error installing doc."
install -vt "$bin" ./emprimt || except "Error installing executable."
echo "Done."
# ----------------------------------------------------------------------------------------

# enable in crontab
# ----------------------------------------------------------------------------------------
echo "Installing crontab..."
[[ "$enable" == true ]] && [[ $( crontab -u "$user" -l | grep -c emprimt ) -eq 0 ]] \
  && crontab -u "$user" - <<< "$interval emprimt" \\
  || except "Error installing crontab."
echo "Done."
# ----------------------------------------------------------------------------------------


echo "Installation complete."
