#!/bin/bash

user=emprimt
bin=/usr/bin
doc=/usr/share/doc/emprimt
interval="05 * * * *"
enable=false
force=false

__doc__=(
  "must be run as superuser."
  "usage: ./install -h"
  "       ./install [ --user <emprimt_user> (default \`$user')"
  "                   --enable (i.e. install cron; default false)"
  "                   --interval <cron_spec> (default \`$interval')"
  "                   --force (i.e. force re-install config) ]"
)

show_doc() {
  printf "%s\n" "${__doc__[@]}" > /dev/stderr
}

if [[ "$USER" != "root" ]]; then show_doc; exit; fi

while [ "$#" -gt 0 ]; do
  case "$1" in
    --user)
      user="$2"
      shift 2
      ;;
    --interval)
      interval="$2"
      shift 2
      ;;
    --enable)
      enable=true
      shift 1
      ;;
    --force)
      force=true
      shift 1
      ;;
    -h)
      show_doc
      exit 1
      ;;
    *)
      show_doc
      exit 1
      ;;
  esac
done

HOME=$( awk -F: '$1=="'$user'" {print $6}' /etc/passwd )
config="$HOME/.emprimt"

setup_user() {
  adduser "$user"
  [[ "$enable" == "true" ]] && crontab -u "$user" - <<< "$interval" emprimt
}

configure() {
  [ ! -d "$HOME/primtbox" ] && sudo -u "$user" maildirmake "$HOME/primtbox"

  cp -v ./mailfilter "$HOME/.mailfilter"
  chown -v "$user" "$HOME/.mailfilter"
  chmod -v 600 "$HOME/.mailfilter"

  touch "$config/printers"
}

[[ $( awk '{print $1}' /etc/passwd | grep -c "$user" ) -eq 0 ]] && setup_user

mkdir -v --parents "$doc" "$config"
cp -v ./doc "$doc/doc"

if [ ! -f "$fetchmailrc" ] || [ "$force" == "true" ]; then configure; fi

install -vt "$bin" ./emprimt
